-- 管理员用户
CREATE TABLE IF NOT EXISTS AdminUser (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  nickname TEXT DEFAULT '博主' NOT NULL,
  avatar TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS AdminUser_username_key ON AdminUser(username);

-- 文章/页面
CREATE TABLE IF NOT EXISTS Post (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  content TEXT DEFAULT '' NOT NULL,
  description TEXT,
  coverImage TEXT,
  status TEXT DEFAULT 'draft' NOT NULL,
  views INTEGER DEFAULT 0 NOT NULL,
  isPage INTEGER DEFAULT 0 NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  authorId INTEGER NOT NULL,
  FOREIGN KEY (authorId) REFERENCES AdminUser(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS Post_slug_key ON Post(slug);
CREATE INDEX IF NOT EXISTS Post_status_idx ON Post(status);
CREATE INDEX IF NOT EXISTS Post_authorId_idx ON Post(authorId);

-- 文章-分类（显式多对多）
CREATE TABLE IF NOT EXISTS PostCategory (
  postId INTEGER NOT NULL,
  categoryId INTEGER NOT NULL,
  PRIMARY KEY (postId, categoryId),
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 文章-标签（显式多对多）
CREATE TABLE IF NOT EXISTS PostTag (
  postId INTEGER NOT NULL,
  tagId INTEGER NOT NULL,
  PRIMARY KEY (postId, tagId),
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (tagId) REFERENCES Tag(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 分类
CREATE TABLE IF NOT EXISTS Category (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT,
  sortOrder INTEGER DEFAULT 0 NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS Category_name_key ON Category(name);
CREATE UNIQUE INDEX IF NOT EXISTS Category_slug_key ON Category(slug);
CREATE INDEX IF NOT EXISTS Category_slug_idx ON Category(slug);

-- 标签
CREATE TABLE IF NOT EXISTS Tag (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  color TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS Tag_name_key ON Tag(name);
CREATE UNIQUE INDEX IF NOT EXISTS Tag_slug_key ON Tag(slug);
CREATE INDEX IF NOT EXISTS Tag_slug_idx ON Tag(slug);

-- 自定义页面
CREATE TABLE IF NOT EXISTS Page (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  content TEXT DEFAULT '' NOT NULL,
  isDefault INTEGER DEFAULT 0 NOT NULL,
  sortOrder INTEGER DEFAULT 0 NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS Page_slug_key ON Page(slug);
CREATE INDEX IF NOT EXISTS Page_slug_idx ON Page(slug);

-- 友链
CREATE TABLE IF NOT EXISTS FriendLink (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  logo TEXT,
  sortOrder INTEGER DEFAULT 0 NOT NULL,
  isActive INTEGER DEFAULT 1 NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 评论
CREATE TABLE IF NOT EXISTS Comment (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  content TEXT NOT NULL,
  authorName TEXT NOT NULL,
  authorEmail TEXT,
  authorUrl TEXT,
  isApproved INTEGER DEFAULT 0 NOT NULL,
  isPinned INTEGER DEFAULT 0 NOT NULL,
  ip TEXT,
  userAgent TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  postId INTEGER NOT NULL,
  parentId INTEGER,
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (parentId) REFERENCES Comment(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS Comment_postId_idx ON Comment(postId);
CREATE INDEX IF NOT EXISTS Comment_isApproved_idx ON Comment(isApproved);
CREATE INDEX IF NOT EXISTS Comment_parentId_idx ON Comment(parentId);

-- 站点配置
CREATE TABLE IF NOT EXISTS SiteSettings (
  id TEXT PRIMARY KEY NOT NULL,
  siteName TEXT DEFAULT '我的博客' NOT NULL,
  siteUrl TEXT DEFAULT '' NOT NULL,
  siteLogo TEXT DEFAULT '' NOT NULL,
  siteFavicon TEXT DEFAULT '' NOT NULL,
  siteDescription TEXT DEFAULT '' NOT NULL,
  themeMode TEXT DEFAULT 'light' NOT NULL,
  themeColors TEXT DEFAULT '{}' NOT NULL,
  fonts TEXT DEFAULT '{}' NOT NULL,
  layout TEXT DEFAULT '{}' NOT NULL,
  homepageModules TEXT DEFAULT '[]' NOT NULL,
  seoConfig TEXT DEFAULT '{}' NOT NULL,
  headCustom TEXT DEFAULT '' NOT NULL,
  footerCustom TEXT DEFAULT '' NOT NULL,
  customCSS TEXT DEFAULT '' NOT NULL,
  navConfig TEXT DEFAULT '[]' NOT NULL,
  commentConfig TEXT DEFAULT '{}' NOT NULL,
  socialLinks TEXT DEFAULT '[]' NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 键值配置
CREATE TABLE IF NOT EXISTS Config (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  key TEXT NOT NULL,
  value TEXT DEFAULT '' NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS Config_key_key ON Config(key);
CREATE INDEX IF NOT EXISTS Config_key_idx ON Config(key);